# version: '3.3'

volumes:
  static_value:
  media_value:
  pg_data:
  docs:
  frontend:

services:
  db:
    image: postgres:15
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ksokolov/foodgram_backend
    depends_on: 
      - db
    env_file: ./.env
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/media/
      - docs:/app/docs/
  frontend:
    container_name: foodgram-front
    image: ksokolov/foodgram_frontend
    volumes:
      - frontend:/app/result_build/build
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - 8090:80
    volumes:
      - static_value:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
      - docs:/usr/share/nginx/html/api/docs/
      - media_value:/app/media/
