version: '3.3'

volumes:
  static_value:
  media_value:
  pg_data:

services:
  db:
    image: postgres:15
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    # image: foodgram-backend:latest
    build: ../backend/
    depends_on: 
      - db
    env_file: ../.env
    volumes:
      - static_value:/app/collected_static/
      - media_value:/app/media/
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - static_value:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
